[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]] 
  name = "github.com/bitrise-io/go-android"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[prune]
  go-tests = true
  unused-packages = true
